### ISSUE TITLE
Add support for direct HTTP URLs (not cloud storage)

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/shaka-streamer#210]
v1.0.0 removed support for direct HTTP output (not cloud storage), to simplify the cloud storage rewrite.  We should add it back.

@jspizziri, please let us know what your requirements are:

1. Do you need support for configurable HTTP headers?
2. Do you need support for any higher level auth tokens?
3. Do you need anything else other than HTTP URLs for output being passed to Packager?

**Comment by jspizziri** [comment]
@joeyparrish thanks for your attention to this, really appreciate it!


> 1. Do you need support for configurable HTTP headers?

We currently do not, but it could be nice. Not required though. We built it such that a signature is part of the base path rather than in a header.

> 2. Do you need support for any higher level auth tokens?

No, not currently.

> 3. Do you need anything else other than HTTP URLs for output being passed to Packager?

No, not currently. We were using it in a pretty vanilla way, where we'd pass a base URL with a signature of sorts as part of the path and then all the chunks get appended to that signed path.

**Comment by joeyparrish** [comment]
Okay, then I'll add something that just allows plain HTTP URLs to be passed to Shaka Packager for output, without ProxyNode or any cloud storage clients.

**Comment by matt5stones** [comment]
@joeyparrish Thanks for the update; this is working for our use case now!

**Comment by joeyparrish** [comment]
Glad to hear it, @matt5stones!
